/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_rallyphysics_free: (a: number, b: number) => void;
export const rallyphysics_add_boxes: (a: number, b: number, c: number) => void;
export const rallyphysics_add_cylinders: (a: number, b: number, c: number) => void;
export const rallyphysics_add_platform: (a: number, b: number, c: number, d: number) => number;
export const rallyphysics_add_platform_pitched: (a: number, b: number, c: number, d: number) => number;
export const rallyphysics_add_surface_boxes: (a: number, b: number, c: number, d: number, e: number) => void;
export const rallyphysics_advance: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const rallyphysics_blend: (a: number) => [number, number];
export const rallyphysics_new: () => number;
export const rallyphysics_remove_platform: (a: number, b: number) => void;
export const rallyphysics_remove_remote: (a: number, b: number) => void;
export const rallyphysics_reset: (a: number, b: number, c: number, d: number, e: number) => void;
export const rallyphysics_select_vehicle: (a: number, b: number) => number;
export const rallyphysics_set_assists: (a: number, b: number) => void;
export const rallyphysics_set_damage: (a: number, b: number, c: number, d: number, e: number) => number;
export const rallyphysics_set_platform: (a: number, b: number, c: number, d: number) => number;
export const rallyphysics_set_roads: (a: number, b: number, c: number) => number;
export const rallyphysics_set_surface_map: (a: number, b: number, c: number) => number;
export const rallyphysics_set_terrain: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const rallyphysics_set_water: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const rallyphysics_snapshot: (a: number) => [number, number];
export const rallyphysics_take_impacts: (a: number) => [number, number];
export const rallyphysics_update_remote: (a: number, b: number, c: number, d: number, e: number) => void;
export const rallyphysics_prop_count: (a: number) => number;
export const rallyphysics_prop_poses: (a: number) => [number, number];
export const rallyphysics_pusher_position: (a: number) => [number, number];
export const rallyphysics_set_prop_solid: (a: number, b: number, c: number) => number;
export const rallyphysics_set_pusher: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const rallyphysics_sleep_prop: (a: number, b: number) => number;
export const rallyphysics_wake_prop: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => number;
export const wasm_bindgen__closure__destroy__h444644dcfe552aba: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h7012d1d11362b952: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb3568c88ea460d32: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5de9179e75b47c10: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
